In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from matplotlib.pyplot import imread, imshow, subplots, show

In [2]:
#data_dir = './data/Animals'
#gen = ImageDataGenerator().flow_from_directory(data_dir, class_mode='categorical')

In [3]:
from tensorflow.keras.datasets import mnist, cifar10

(X_train, y_train), (X_val, y_val) = mnist.load_data()
X_train = X_train[:,:,:,np.newaxis]
y_train = tf.keras.utils.to_categorical(y_train)
y_val = tf.keras.utils.to_categorical(y_val)

In [ ]:
#X, y = next(gen)

In [21]:

'''import os

to_rename = gen.filepaths
extensions = set()
for p in to_rename:
    split = p.split('/')
    path = '/'.join(split[:-1])
    fname = split[-1]
    fname_split = fname.split('.')
    new_fname = '_'.join(fname_split[:-1]) + '.' + fname_split[-1]
    extensions.add(fname_split[-1])
    new_full_path = os.path.join(path, new_fname)
    os.rename(p, new_full_path)
'''

FileNotFoundError: [Errno 2] No such file or directory: './data/Animals/Cat/AdorableBlackCatLookingAtCameraFromSofa.jpg.653x0_q80_crop-smart.jpg' -> './data/Animals/Cat/AdorableBlackCatLookingAtCameraFromSofa_jpg_653x0_q80_crop-smart.jpg'

In [64]:
from tensorflow.keras.layers import Conv2D, Dense, MaxPool2D, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [72]:

model = tf.keras.Sequential([
    Conv2D(64, (5,5), input_shape = X_train.shape[1:], activation='relu'),
    Conv2D(64, (5,5), activation='relu'),
    MaxPool2D(),
    
    Conv2D(128, (3,3), activation='relu'),
    Conv2D(128, (3,3), activation='relu'),
    MaxPool2D(),
    
    Flatten(),
    
    Dense(64, activation='relu'),
    Dense(y_train.shape[1], activation='softmax')    
])

adam = Adam(learning_rate = 0.001)
model.compile(optimizer=adam, 
              loss=CategoricalCrossentropy(), 
              metrics=['acc'])

model.summary()


Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_28 (Conv2D)           (None, 24, 24, 64)        1664      
_________________________________________________________________
conv2d_29 (Conv2D)           (None, 20, 20, 64)        102464    
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 10, 10, 64)        0         
_________________________________________________________________
conv2d_30 (Conv2D)           (None, 8, 8, 128)         73856     
_________________________________________________________________
conv2d_31 (Conv2D)           (None, 6, 6, 128)         147584    
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 3, 3, 128)         0         
_________________________________________________________________
flatten_7 (Flatten)          (None, 1152)             

In [74]:
model.fit(X_train, y_train, batch_size=32, shuffle=True, epochs=1, verbose=1)

Train on 60000 samples
 2656/60000 [>.............................] - ETA: 5:36 - loss: 0.3899 - acc: 0.8937

KeyboardInterrupt: 

In [39]:
#model.fit_generator(gen,steps_per_epoch=gen.n//32,epochs=1)

4/4 [==============================] - 191s 48s/step - loss: 13.9274 - acc: 0.1327


In [44]:
history.history

{'loss': [13.421838098642777], 'acc': [0.13265306]}

In [48]:
(X_train, ) = mnist.load_data()

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [53]:
mnist.

Signature: mnist.load_data(path='mnist.npz')
Docstring:
Loads the MNIST dataset.

Arguments:
    path: path where to cache the dataset locally
        (relative to ~/.keras/datasets).

Returns:
    Tuple of Numpy arrays: `(x_train, y_train), (x_test, y_test)`.

License:
    Yann LeCun and Corinna Cortes hold the copyright of MNIST dataset,
    which is a derivative work from original NIST datasets.
    MNIST dataset is made available under the terms of the
    [Creative Commons Attribution-Share Alike 3.0 license.](
    https://creativecommons.org/licenses/by-sa/3.0/)
File:      ~/opt/anaconda3/envs/ds/lib/python3.7/site-packages/tensorflow_core/python/keras/datasets/mnist.py
Type:      function


In [ ]:
history = model

In [4]:
(a, b), (c, d) = cifar10.load_data()

In [14]:
train_cut = np.where(b < 8)[0]
val_cut = np.where(d < 8)[0]

X_train = a[train_cut]
y_train = tf.keras.utils.to_categorical(b[cut])

X_val = c[val_cut]
y_val = d[val_cut]

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [8]:
np.unique(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [13]:
a[cut]

array([[[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        